name = "Base58"
uuid = "a832ea1e-0ca7-55ca-a41a-6462721bb861"
authors = ["Guido Kraemer <gdkrmr@users.noreply.github.com>"]
version = "0.3.0"

[compat]
julia = "0.7, 1"

[deps]
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
